### PR TITLE
fix(usSpinnerConfig): fix problem with default options overwriting

### LINKED ISSUE #76: multiple spinners with different options?
It seems that once a spinner is started the config options that are passed into that spinner override any other config options that are passed into any additional spinners on the page. Is this a bug or intended behavior or am I just doing something wrong?

Here's a plunker to illustrate: http://plnkr.co/edit/XLK0emyBzDij0pYv6EqO?p=preview

### PR DESCRIPTION
**Pull request by dmytroyarmak**
Fix problem when default options of usSpinnerConfig are overwritten by theme options and/or spinner options due to incorrect usage of angular.extend.

Fix #76 

And it fixes the same problem as https://github.com/urish/angular-spinner/pull/78 does, but this one has tests.

### CODE REVIEW

**Comment by urish** [comment]
great, thanks!

**Comment by m00s** [comment]
@urish Could you please cut a release with this fix?

**Comment by urish** [comment]
I will

**Comment by urish** [comment]
Released as 0.8.1

**Comment by m00s** [comment]
@urish Awesome. Many thanks

**Pull request merged**
