### PR TITLE
start/stop to support regex

### LINKED ISSUE #28: Feature: Stop all/Start all spinners
Hi,

I need to stop all spinners if server responds with error. Currently it is not possible.

I would implement it with oneliner:
angular-spinner.js:

```
scope.$on('us-spinner:stop', function (event, key) {
    if (key === scope.key || key === undefined) {
        scope.stop();
    }
});
```

### PR DESCRIPTION
**Pull request by marknadig**
Resolves #28 . Updated tests and README.

### CODE REVIEW

**Comment by urish** [comment]
I believe that now that we have `spinner-on` we no longer need this...

**Comment by marknadig** [comment]
@urish I'm fine either way.  Do you anticipate deprecating spinner-key? If not, regex support is handy, but not blocking.

**Comment by MangeshPimpalkar** [comment]
There is no mention of regex on readme.We should put regex feature in readme.

**Comment by MangeshPimpalkar** [comment]
@urish Please let me know when this feature will be release.

**Comment by mkhanal** [comment]
@urish Is there any plan to release this ? Looks like its almost been a year.

**Comment by Attrash-Islam** [comment]
Hi @marknadig ,
Thanks for your contribution :+1: .

We've decided to refactor the whole code base because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

Can you please fix this with the new code-base in master so we can check it and merge it if needed?

**Comment by Attrash-Islam** [comment]
The author of this pull request can't fix it in the meanwhile as stated in the issues, and since Uri (author of angular-spinner) says that this not needed, then I'll close this pull request "meanwhile".

**Pull request closed without merging**
