### PR TITLE
Fix when using dynamic spinner key

### PR DESCRIPTION
**Pull request by ryancat**
Signed-off-by: Ryan Chen ryan.chen@turn.com

### CODE REVIEW

**Comment by ryancat** [comment]
This is to fix #45

**Comment by ryancat** [comment]
Can someone merge this?

**Comment by Attrash-Islam** [comment]
Hi @ryancat ,
Thanks for your contribution :+1: .

We've decided to refactor the whole code base because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

Can you please fix this first and explain how this code is helping?

**Comment by Attrash-Islam** [comment]
Closing for deprecated pull-requests

**Pull request closed without merging**
