### PR TITLE
Added example page and post install scripts

### PR DESCRIPTION
**Pull request by alex-charos**
Added an example folder where the js is copied after the build. The example page is identical to the plunker at http://plnkr.co/edit/BGLUYcylbIVJRz6ztbhf?p=preview

Also added post install in package.json to speed up the bower components fetching (for the example page) and build.

### CODE REVIEW

**Comment by urish** [comment]
Thanks for your contribution, great idea!

Before we can merge it, several things that needs to be addressed:

1. We don't want to add `bower` and `grunt-contrib-copy` to `dependencies`, rather to `devDependencies`, so they don't get installed if you just want to use the package from npm.

2. Similarly, we don't want to run `bower install` and `grunt dist` inside the `postinstall` npm phase, as this means that everyone who consumes the package through npm will also run these commands, 

3. We don't want to have `angular-spinner.js` committed inside the `example` directory. It should be git ignored, as it can automatically created by the grunt task.

4. Finally, there should be a note inside the README file, explaining how to run the example. 

I believe that the best way would be to change the `postinstall` script into `example`, so users will be able to invoke it by simply typing `npm run example`, but it will not be run whenever someone pulls the packages via npm.

Thanks!

**Comment by alex-charos** [comment]
There you go Uri!

**Comment by alex-charos** [comment]
(undoing close pull request :))

**Comment by urish** [comment]
Thanks!

**Comment by Attrash-Islam** [comment]
Hi @alex-charos ,
Thanks for your contribution.

We've decided to refactor the whole base code because of the many requests of webpack and amd compatibility issues, and we're using already webpack in master branch (+TypeScript).

Can you please fix this with the new code-base in master so we can merge it?

**Pull request closed without merging**
